name: CI Backend

on:
  push:
    branches: [ "master", "developer" ]
  pull_request:
    branches: [ "master", "developer" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Tests
      run: dotnet test -c Release --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput="${GITHUB_WORKSPACE}/lcov.info"

    - name: Run Codacy Analysis CLI
      uses: codacy/codacy-analysis-cli-action@97bf5df3c09e75f5bcd72695998f96ebd701846e
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        verbose: true
        output: results.sarif
        format: sarif
        gh-code-scanning-compat: true
        max-allowed-issues: 2147483647

        
    - name: Upload SARIF results file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif

        
    - name: Send Coverage to Codacy
      run: |
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
        --project-token=${{ secrets.CODACY_PROJECT_TOKEN }} \
        --coverage-reports="${GITHUB_WORKSPACE}/lcov.info"
