name: CI

on:
  push:
    branches:
      - main # Change this to your main branch name if different
  pull_request:
    branches:
      - main # Change this to your main branch name if different

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0' # Specify the .NET version you are using

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --output ./output
